services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bookworm 
    environment:
      BOOKSHELF_TEST: /workspaces/.devcontainer/config.js
      MYSQL_USER: bookshelf-test-user
      MYSQL_PASSWORD: bookshelf-test-password
      POSTGRES_USER: bookshelf-test-user
      POSTGRES_PASSWORD: bookshelf-test-password
    volumes:
      - ..:/workspaces:cached
    networks:
      - dev_network
    command: sleep infinity

  postgres:
    image: postgres:9
    restart: unless-stopped
    environment:
      POSTGRES_DB: bookshelf_test
      POSTGRES_USER: bookshelf-test-user
      POSTGRES_PASSWORD: bookshelf-test-password
    networks:
      - dev_network

  mysql:
    image: mysql:5
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: bookshelf_test
      MYSQL_USER: bookshelf-test-user
      MYSQL_PASSWORD: bookshelf-test-password
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
