name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: bookshelf_test
          POSTGRES_USER: bookshelf-test-user
          POSTGRES_PASSWORD: bookshelf-test-password 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql:5
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: bookshelf
          MYSQL_DATABASE: bookshelf_test
          MYSQL_USER: bookshelf-test-user
          MYSQL_PASSWORD: bookshelf-test-password 
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          BOOKSHELF_TEST: ${{ github.workspace }}/.github/workflows/config.js
          POSTGRES_USER: bookshelf-test-user
          POSTGRES_PASSWORD: bookshelf-test-password 
          MYSQL_USER: bookshelf-test-user
          MYSQL_PASSWORD: bookshelf-test-password 
